### ISSUE TITLE
Why we need Both WOFF and TTF for Moztt

### ISSUE THREAD

**Issue by anivar** [mozilla-b2g/moztt#61]
can someone clarify ? 
Do we have both ttf and WOFF on device ? 
I think if GAIA is optimized with @ font-face we need WOFF alone . WOFF will be half size of sfd and we can reduce footprint .  Else TTF alone will be sufficient , because websites with local tag on @font-face can read from  ttf fonts in device  .

**Comment by davelab6** [comment]
I recommend only woff2 on devices

**Comment by anivar** [comment]
I think woff2 have issues with Firefox http://caniuse.com/#feat=woff2

**Comment by davelab6** [comment]
I recommend woff only until its supported, then :)
